//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Error404_TLT.Models.Error404Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.CTOrder = new HashSet<CTOrder>();
        }
    
        public int MaDH { get; set; }
        public Nullable<int> TongDH { get; set; }
        public Nullable<int> TongSP { get; set; }
        public Nullable<int> TongDC { get; set; }
        public Nullable<int> TongShip { get; set; }
        public string User { get; set; }
        public string DCID { get; set; }
        public string Address { get; set; }
        public string ThanhPho { get; set; }
        public string Quan { get; set; }
        public string Phuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTOrder> CTOrder { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
